### PR TITLE
Additional Builders/Schematics - Prisma

### PR DESCRIPTION
**Pull request by wSedlacek**
fixes: #11

@gperdomor 
Here is my initial proposal for `nx-prisma`.
Let me know if you have any feedback.

One other change I considered was moving the utilities to `@gperdomor/utils` so that they could be shared between each library, however I wanted to check with you before making such a change.

## Update for additional details

Implements `nx-prisma` and `examples-prisma`
Refactors `example-app` to `examples-docker`

### Currently supported
```sh
yarn test nx-prisma
yarn build nx-prisma
yarn nx generate examples-prisma
yarn nx rollback examples-prisma
yarn nx migrations examples-prisma
yarn nx seed examples-prisma
```

### In a future PR
- Support user inputs after build has started (for naming migrations etc.)
- Support for specifying `.env` file and variables
- Additional logging/user feedback in CLI
- Additional e2e testing
- Additional documentation
- Schematics for adding `prisma` to an existing project or creating a new project for prisma

### CODE REVIEW

**Comment by gperdomor** [comment]
@wSedlacek Hi... I will check this ASAP...

I like the idea of some kind of libraries to handle common code... let's discuss that after the merge 👍

**Comment by gperdomor** [comment]
@wSedlacek can you put back the examples in apps folder (outside example folder)... I'm worried about how that can impact in nx migrations...

**Comment by wSedlacek** [comment]
For sure. Are alright we the renaming to example-docker from example-app?

**Comment by gperdomor** [comment]
@wSedlacek yes please

**Pull request merged**
