### PR TITLE
feat: core lib

### LINKED ISSUE #18: Feature Request: Core library for common code
From #16 
> One other change I considered was moving the utilities to @gperdomor/utils so that they could be shared between each library, however I wanted to check with you before making such a change.

This issue is to discuss a common library to be shared across builder/schematic libraries and determine what such a library should look like, include and what benefits it might offer.

### PR DESCRIPTION
**Pull request by gperdomor**
Fix #18

### CODE REVIEW

**Comment by gperdomor** [comment]
@wSedlacek please take a look 😄

**Comment by wSedlacek** [comment]
This looks like a great start.
The biggest thing I am noticing is that `@nrwl/workspace` is missing as a dependency from `@nx-tools/core` which we are using for the 10MB constant.

If that is the only thing we are using it for we may consider using another library or simply providing our own constants to simplify the dependencies.

**Comment by gperdomor** [comment]
I think we can put a constant file inside the core lib, at leats for now, to not create a new lib for that and not using @nrwl/workspace for only one constant 🤔

**Comment by wSedlacek** [comment]
> I think we can put a constant file inside the core lib, at leats for now, to not create a new lib for that and not using @nrwl/workspace for only one constant 🤔

👍  I agree. If we do need more constants for MBs or GBs we may consider building something like [ms](https://www.npmjs.com/package/ms) for time. I like to wrap `ms` in a template function so I can use it like so
```ts
const day = ms`1d`
```

I doubt we will need any more MB constants though.

**Comment by gperdomor** [comment]
@wSedlacek @nx-tools/core should be a dependency or peerDependency? 🤔

**Comment by wSedlacek** [comment]
Dependency. A consumer of the library should not be required to install @nx-tools/core directly

**Comment by gperdomor** [comment]
@wSedlacek please try the published alpha and let me know if everything works as expected

**Comment by wSedlacek** [comment]
> @wSedlacek please try the published alpha and let me know if everything works as expected

Everything is working as expected with `nx-prisma`

**Pull request merged**
